### ISSUE TITLE
Feature request: Inherit default FZF layout

### ISSUE THREAD

**Issue by r7vme** [zackhsi/fzf-tags#13]
Hi, thanks for the plugin.

[FZF recently switched](https://github.com/junegunn/fzf/commit/c60ed1758315f0d993fbcbf04459944c87e19a48) to floating pop-up window by default (It works in my NeoVIM 0.4.4), but fzf-tags use predefined `{ 'down': '~40%' }`. Because I use both native FZF functionality and your plugin I found it useful to have same layout.

Would be great if fzf-tags can inherit the same default layout that is used in FZF.

For now I just hard-coded floating window

```
diff --git a/autoload/fzf_tags.vim b/autoload/fzf_tags.vim
index 06033d4..ec73898 100644
--- a/autoload/fzf_tags.vim
+++ b/autoload/fzf_tags.vim
@@ -40,7 +40,7 @@ function! fzf_tags#Find(identifier)
     \   'source': source_lines,
     \   'sink*':   function('s:sink', [identifier]),
     \   'options': '--expect=' . expect_keys . ' --ansi --no-sort --tiebreak index --prompt "' . g:fzf_tags_prompt . '\"' . identifier . '\" > "',
-    \   'down': '40%',
+    \   'window' : { 'width': 0.9, 'height': 0.6, 'highlight': 'Normal' },
     \ })
   endif
 endfunction
```

Example floating window
![1](https://user-images.githubusercontent.com/1277504/104713231-e1e0a580-5723-11eb-98c1-33291bb3e172.jpg)

**Comment by zackhsi** [comment]
Thanks! I've added support for `g:fzf_layout` in #14.
