### ISSUE TITLE
Why use `--no-sort`?

### ISSUE THREAD

**Issue by umayr** [zackhsi/fzf-tags#3]
I'm curious why sorting is disabled when searching within the results? I personally find it inconvenient. Was there any particular reason behind using `--no-sort`?

Link: https://github.com/zackhsi/fzf-tags/blob/master/autoload/fzf_tags.vim#L23

**Comment by zackhsi** [comment]
The tags are already sorted by relevancy, by passing the filename as context to `taglist`.

https://github.com/zackhsi/fzf-tags/blob/adfdaee9166db8edfbc81be92957493c1cb55c8a/autoload/fzf_tags.vim#L39

From `:help taglist`:
> If {filename} is passed it is used to prioritize the results
> in the same way that |:tselect| does. See |tag-priority|.
> {filename} should be the full path of the file.

From `:help tag-priority`:
> When there are multiple matches for a tag, this priority is used:
> 1. "FSC"  A full matching static tag for the current file.
> 2. "F C"  A full matching global tag for the current file.
> 3. "F  "  A full matching global tag for another file.
> 4. "FS "  A full matching static tag for another file.
> 5. " SC"  An ignore-case matching static tag for the current file.
> 6. "  C"  An ignore-case matching global tag for the current file.
> 7. "   "  An ignore-case matching global tag for another file.
> 8. " S "  An ignore-case matching static tag for another file.

Cheers!

**Comment by umayr** [comment]
Makes sense. Thank you for your explanation.
